<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SspBlog\Controller\BlogController' => __DIR__ . '/src/SspBlog/Controller/BlogController.php',
    'SspBlog\Module'                       => __DIR__ . '/Module.php',
    'SspBlogTest\SampleTest'               => __DIR__ . '/tests/SspBlog/SampleTest.php',
    'SspBlogTest\Framework\TestCase'       => __DIR__ . '/tests/SspBlog/Framework/TestCase.php',
);
